Library_management2/Controllers/AdminTransController.cs
using Library_management2.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Library_management2.Controllers
{
    public class AdminTransController : Controller
    {
        private LibraryManagementEntities1 db = new LibraryManagementEntities1();

        // Returns admin request view, here admin can accept and reject the book requests
        public ActionResult Requests()
        {
            return View(db.Transactions.ToList());
        }
        // Returns all book requests in json format.
        public ActionResult GetAllRequests()
        {
                db.Configuration.ProxyCreationEnabled = false;
                var transactionList = db.Transactions
                .Where(r => r.TransStatus == "Requested")
                .Select(t => new TransactionViewModel
                {
                    BookTitle = t.BookTitle,
                    TansDate = t.TansDate,
                    UserName = t.UserName,
                    TransID = t.TransID,

                })
                .ToList();
                return Json(new {data = transactionList}, JsonRequestBehavior.AllowGet); 
        }
        // Accepts the book request.
        public ActionResult AcceptRequest(int? tranId)
        {
            /* try
             {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.FirstOrDefault(t => t.TransID == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            transaction.TransStatus = "Accepted";
            transaction.TansDate = DateTime.Now;
            db.SaveChanges();
            return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/

        }
        // Reject the book request. 
        public ActionResult RejectRequest(int? tranId)
        {
            /*try
            {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.FirstOrDefault(t => t.TransID == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            transaction.TransStatus = "Rejected";
            transaction.TansDate = DateTime.Now;
            Book book = db.Books.FirstOrDefault(b => b.BookID == transaction.BookID);
            book.BookCopies = book.BookCopies + 1;
            db.SaveChanges();
            db.SaveChanges();
            return View("Requests");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
        // Returns admin accepted view, here admin can view the accepted books.
        public ActionResult Accepted()
        {
            return View(db.Transactions.ToList());
        }
        // Returns all accepted books in json format.
        public ActionResult GetAllAccepted()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var transactionList = db.Transactions
            .Where(r => r.TransStatus == "Accepted")
            .Select(t => new TransactionViewModel
            {
                BookTitle = t.BookTitle,
                TansDate = t.TansDate,
                UserName = t.UserName,
                TransID = t.TransID,

            })
            .ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Returns admin return view, here admin can accept book return requests.
        public ActionResult Return()
        {
            return View(db.Transactions.ToList());
        }
        // Returns all return books in json format.
        public ActionResult GetAllReturn()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var transactionList = db.Transactions
            .Where(r => r.TransStatus == "Returned")
            .Select(t => new TransactionViewModel
            {
                BookTitle = t.BookTitle,
                TansDate = t.TansDate,
                UserName = t.UserName,
                TransID = t.TransID,

            })
            .ToList();
            return Json(new { data = transactionList }, JsonRequestBehavior.AllowGet);
        }
        // Accepts the book return request.
        public ActionResult AcceptReturn(int? tranId)
        {

            /*try
            {*/
            if (tranId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.FirstOrDefault(t => t.TransID == tranId);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            Book book = db.Books.FirstOrDefault(b => b.BookID == transaction.BookID);
            book.BookCopies = book.BookCopies + 1;
            db.SaveChanges();
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return View("Return");
            /*}
            catch (Exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }*/
        }
    }
}

Library_management2/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library_management2.Models;

namespace Library_management2.Controllers
{
    public class AdminsController : Controller
    {
        private LibraryManagementEntities1 db = new LibraryManagementEntities1();

        // Returns admin login view, here admin can login.
        [HttpGet]
        [HandleError]
        public ActionResult Login()
        {
            return View();
        }

        // Checks admin credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        [HandleError]
        public ActionResult Login(Admin admin)
        {
            var adm = db.Admins.SingleOrDefault(a => a.AdminEmail == admin.AdminEmail && a.AdminPass == admin.AdminPass);
            if (adm != null)
            {
                int id = adm.AdminID;
                Session["adminId"] = adm.AdminID;
                return RedirectToAction("Index", "Books", new { id = id });
            }
            else if (admin.AdminEmail == null && admin.AdminPass == null)
            {
                return View();
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }

        // Admin logout, redirect to main. 
        [HandleError]
        public ActionResult Logout()
        {
            Session.Remove("adminId");
            return RedirectToAction("Home", "Home");
        }

        // GET: Admins/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Admin admin = db.Admins.Find(id);
            if (admin == null)
            {
                return HttpNotFound();
            }
            return View(admin);
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AdminID,AdminName,AdminEmail,AdminPass")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                db.Admins.Add(admin);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(admin);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Library_management2/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Library_management2.Models;

namespace Library_management2.Controllers
{
    public class BooksController : Controller
    {
        private LibraryManagementEntities1 db = new LibraryManagementEntities1();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        public ActionResult GetAll()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var booklist = db.Books.ToList();
            return Json(new { data = booklist }, JsonRequestBehavior.AllowGet);
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookID,BookTitle,BookCategory,BookAuthor,BookCopies,BookPubName,Copyrights,DateAdded,Status")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookID,BookTitle,BookCategory,BookAuthor,BookCopies,BookPubName,Copyrights,DateAdded,Status")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /*protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }*/
    }
}

Library_management2/Controllers/UserLoginController.cs
using Library_management2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library_management2.Controllers
{
    public class UserLoginController : Controller
    {
        LibraryManagementEntities1 userDb = new LibraryManagementEntities1();

        // Returns user login view, here admin can login.
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        // Checks user credentials, redirecting to admin section (index, tblBooks). 
        [HttpPost]
        public ActionResult Login(User user)
        {
            var adm = userDb.Users.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserID;
                Session["userName"] = adm.UserName;
                return RedirectToAction("Index", "Borrow", new { userId = adm.UserID, userName = adm.UserName });
            }
            else if (user.UserEmail == null && user.UserPass == null)
            {
                return View();
            }
            ViewBag.Message = "User name and password are not matching";
            return View();
        }

        /* User credentials validation two
        public ActionResult Validate(tblUser user)
        {
            var adm = db.tblUsers.SingleOrDefault(a => a.UserEmail == user.UserEmail && a.UserPass == user.UserPass);
            if (adm != null)
            {
                Session["userId"] = adm.UserId;
                Session["userName"] = adm.UserName;
                ViewBag.userId= adm.UserId;
                ViewBag.userId = adm.UserId;
                return RedirectToAction("Index", "Borrow", new { userId = adm.UserId, userName = adm.UserName });
            }
               else if (user.UserEmail == null && user.UserPass == null)
            {
                return View("Login");
            }
            ViewBag.Message = "User name and password are not matching";
            return View("Login");
        }
        */

        // User logout, redirect to main. 
        public ActionResult Logout()
        {
            Session.Remove("userId");
            Session.Remove("userName");
            return RedirectToAction("Home", "Home");
        }
    }
}

Library_management2/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sydenham Library</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#5cb85c;">
            <div style="background-color:#d9534f; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("Sydenham Library", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-success">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Books", "Index", "Books", new { area = "" }, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Users", "Index", "Users", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px">
                        @Html.ActionLink("Request", "Requests", "AdminTrans", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Accepted", "Accepted", "AdminTrans", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Return", "Return", "AdminTrans", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                </ul>
                <span class="text-light" style="padding-top:1px; padding-right:15px">Welcome back Admin!!</span>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item btn btn-sm btn-success">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "Admins", null, new { @class = "nav-link", onclick = "return alert('Logged out successfully');", style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-white bg-success">
                <div class="card-header">
                    Thank you for your work
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - Sydenham Library</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#5cb85c;">
        <div style="background-color:#d9534f; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Library_management2/Views/Shared/MainView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sydenham Library</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#d9534f;">
            <div style="background-color:#292b2c; height:8px; width:450px">
            </div>
        </div>
        <div>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <span class="icon">
                    <i class="fas fa-book-open"></i>
                </span>
                @Html.ActionLink("Sydenham Library", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item btn-sm btn-dark">
                            <i class="fas fa-home"></i>
                            @Html.ActionLink("Home", "Home", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                        </li>
                        <li class="nav-item btn-sm btn-dark">
                            <i class="fas fa-book-open"></i>
                            @Html.ActionLink("Books", "Login", "UserLogin", null, new { @class = "nav-link icon", style = "display:inline" })
                        </li>
                        <li class="nav-item btn-sm btn-dark">
                            <i class="fas fa-address-card"></i>
                            @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                        </li>
                        <li class="nav-item btn-sm btn-dark">
                            <i class="fas fa-id-badge"></i>
                            @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                        </li>
                    </ul>

                    <ul class="navbar-nav justify-content-end">
                        <li class="nav-item btn-sm btn-dark">
                            <i class="fas fa-sign-in-alt"></i>
                            @Html.ActionLink("Login", "Login", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        

    </div>
    <div style="padding-left:20px; padding-right:20px;">
        @RenderBody()
    </div>
    <div>
        <footer>
            <div style="" class="card text-center text-white bg-dark">
                <div class="card-header">
                    Thank you for visiting us
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - Sydenham Library</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#d9534f;">
        <div style="background-color:#292b2c; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Library_management2/Views/Shared/UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sydenham Library</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
    <link href="~/Content/lmscustom.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#d9534f;">
            <div style="background-color:#5cb85c; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("Sydenham Library", "MenuBorrow", "Borrow", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "Home", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-danger">
                        <i class="fas fa-id-badge"></i>
                        @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link icon", style = "display:inline" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">
                        @Html.ActionLink("Borrow", "MenuBorrow", "Borrow", new { area = "" }, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Requested", "MenuRequested", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                    </li>
                    <li style="padding-left: 5px; padding-right: 5px ">
                        @Html.ActionLink("Received", "MenuReceived", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })

                    </li>
                    <li class="" style="padding-left:5px; padding-right:10px">
                        @Html.ActionLink("Rejected", "MenuRejected", "Borrow", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })

                    </li>
                </ul>
                <span class="text-light" style="padding-top:1px; padding-right:15px">Welcome back @Session["userName"]!!</span>
                <ul class="navbar-nav justify-content-end">

                    <li class="nav-item btn btn-sm btn-danger">
                        <i class="fas fa-sign-out-alt"></i>
                        @Html.ActionLink("Logout", "Logout", "UserLogin", null, new { @class = "nav-link", onclick = "return alert('Logged out successfully');", style = "display:inline" })
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-white bg-danger">
                <div class="card-header">
                    Thank you for visiting us
                </div>
                <div class="card-body">
                    <h5 class="card-title">Social Platforms</h5>
                    <div style="width: auto;" class="form-group">
                        <span>
                            <i class="fab fa-facebook-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-twitter-square"></i>
                        </span>
                        <span>
                            <i class="fab fa-instagram"></i>
                        </span>
                    </div>
                </div>
                <p>&copy; @DateTime.Now.Year - Sydenham Library</p>
            </div>
        </footer>
    </div>
    <div style="background-color:#d9534f;">
        <div style="background-color:#5cb85c; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>